name: ci-cd-training
on:
  push:
      branches:
              - master

jobs:
    build:
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v3
            with:
              ref: master

          - name: Deploy the file on EC2 
            run: 
              mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
              ssh-keyscan -t rsa  ec2-18-208-218-175.compute-1.amazonaws.com >> ~/.ssh/known_hosts
              chmod 400 cicdpipeline.pem
              scp -1 "cicdpipeline.pem" cicd.html ssh -i "cicdpipeline.pem" ubuntu@ec2-18-208-218-175.compute-1.amazonaws.com:/var/www/html/ 
    
    
